name: Run Tests and Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run Tests
      working-directory: ./frontend
      run: npm run test:ci
      env:
        CI: true

  deployment:
    needs: test
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "."
          target: "/home/ubuntu/bank-docker-aws"

      - name: Execute deployment script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: 22
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "NEXT_PUBLIC_BACKEND_URL=${{ secrets.NEXT_PUBLIC_BACKEND_URL }}" > /home/ubuntu/dockerbankcicd/.env
            echo "DB_USER=${{ secrets.DB_USER }}" >> /home/ubuntu/dockerbankcicd/.env
            echo "DB_PASS=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> /home/ubuntu/dockerbankcicd/.env
            echo "DB_NAME=${{ secrets.MYSQL_DATABASE }}" >> /home/ubuntu/dockerbankcicd/.env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> /home/ubuntu/dockerbankcicd/.env
            cd /home/ubuntu/dockerbankcicd
            docker-compose down
            docker-compose up --build -d